#!/usr/bin/env bash
#check if installed
if [ ! -d ~/.gw ]; then
    echo "Please run 'make install' first.";
    exit;
fi;

#goto install directory
cd ~/.gw;
#start the GUI
java -jar gridworld.jar &> .gwlog &
